version: '2'

networks:
  default:

services:

  orderer.hf.Shivam.com:
    image: hyperledger/fabric-orderer:x86_64-1.0.5
    container_name: orderer.hf.Shivam.com
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISPROFILE=OrdererGenesis
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=hf.Shivam.com
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./artifacts/orderer.genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/hf.Shivam.com/orderers/orderer.hf.Shivam.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/hf.Shivam.com/orderers/orderer.hf.Shivam.com/tls:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050
    networks:
      default:
        aliases:
          - orderer.hf.Shivam.com

  ca.org1.hf.Shivam.com:
    image: hyperledger/fabric-ca:x86_64-1.0.5
    container_name: ca.org1.hf.Shivam.com
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org1.hf.Shivam.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.hf.Shivam.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/78cc5d321e82b54895160bfc2b3a667cfddfb4b21650cbe0b261e086acc9363e_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.hf.Shivam.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/78cc5d321e82b54895160bfc2b3a667cfddfb4b21650cbe0b261e086acc9363e_sk
    ports:
      - 7054:7054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.Shivam.com/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      default:
        aliases:
          - ca.org1.hf.Shivam.com

  peer0.org1.hf.Shivam.com:
    image: hyperledger/fabric-peer:x86_64-1.0.5
    container_name: peer0.org1.hf.Shivam.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_NETWORKID=Shivam
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
      - CORE_PEER_ID=peer0.org1.hf.Shivam.com
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_ADDRESS=peer0.org1.hf.Shivam.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.hf.Shivam.com:7051
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_LOCALMSPID=org1.hf.Shivam.com
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
      - CORE_PEER_TLS_SERVERHOSTOVERRIDE=peer0.org1.hf.Shivam.com
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.hf.Shivam.com/peers/peer0.org1.hf.Shivam.com/msp:/var/hyperledger/msp
      - ./crypto-config/peerOrganizations/org1.hf.Shivam.com/peers/peer0.org1.hf.Shivam.com/tls:/var/hyperledger/tls
    ports:
      - 8001:7051
      - 8003:7053
    depends_on:
      - orderer.hf.Shivam.com
    links:
      - orderer.hf.Shivam.com
     #- mongodb
    networks:
      default:
        aliases:
          - peer0.org1.hf.Shivam.com

  peer1.org1.hf.Shivam.com:
    image: hyperledger/fabric-peer:x86_64-1.0.5
    container_name: peer1.org1.hf.Shivam.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_NETWORKID=Shivam
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
      - CORE_PEER_ID=peer1.org1.hf.Shivam.com
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_ADDRESS=peer1.org1.hf.Shivam.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.hf.Shivam.com:7051
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_LOCALMSPID=org1.hf.Shivam.com
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
      - CORE_PEER_TLS_SERVERHOSTOVERRIDE=peer1.org1.hf.Shivam.com
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.hf.Shivam.com/peers/peer1.org1.hf.Shivam.com/msp:/var/hyperledger/msp
      - ./crypto-config/peerOrganizations/org1.hf.Shivam.com/peers/peer1.org1.hf.Shivam.com/tls:/var/hyperledger/tls
    ports:
      - 8011:7051
      - 8013:7053
    depends_on:
      - orderer.hf.Shivam.com
    links:
      - orderer.hf.Shivam.com
    networks:
      default:
        aliases:
          - peer1.org1.hf.Shivam.com

  peer2.org1.hf.Shivam.com:
    image: hyperledger/fabric-peer:x86_64-1.0.5
    container_name: peer2.org1.hf.Shivam.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_NETWORKID=Shivam
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
      - CORE_PEER_ID=peer2.org1.hf.Shivam.com
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_ADDRESS=peer2.org1.hf.Shivam.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.org1.hf.Shivam.com:7051
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_LOCALMSPID=org1.hf.Shivam.com
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
      - CORE_PEER_TLS_SERVERHOSTOVERRIDE=peer2.org1.hf.Shivam.com
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.hf.Shivam.com/peers/peer2.org1.hf.Shivam.com/msp:/var/hyperledger/msp
      - ./crypto-config/peerOrganizations/org1.hf.Shivam.com/peers/peer2.org1.hf.Shivam.com/tls:/var/hyperledger/tls
    ports:
      - 8021:7051
      - 8023:7053
    depends_on:
      - orderer.hf.Shivam.com
    links:
      - orderer.hf.Shivam.com
    networks:
      default:
        aliases:
          - peer2.org1.hf.Shivam.com

  peer3.org1.hf.Shivam.com:
    image: hyperledger/fabric-peer:x86_64-1.0.5
    container_name: peer3.org1.hf.Shivam.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_NETWORKID=Shivam
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
      - CORE_PEER_ID=peer3.org1.hf.Shivam.com
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_ADDRESS=peer3.org1.hf.Shivam.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer3.org1.hf.Shivam.com:7051
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_LOCALMSPID=org1.hf.Shivam.com
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
      - CORE_PEER_TLS_SERVERHOSTOVERRIDE=peer3.org1.hf.Shivam.com
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.hf.Shivam.com/peers/peer3.org1.hf.Shivam.com/msp:/var/hyperledger/msp
      - ./crypto-config/peerOrganizations/org1.hf.Shivam.com/peers/peer3.org1.hf.Shivam.com/tls:/var/hyperledger/tls
    ports:
      - 8031:7051
      - 8033:7053
    depends_on:
      - orderer.hf.Shivam.com
    links:
      - orderer.hf.Shivam.com
    networks:
      default:
        aliases:
          - peer3.org1.hf.Shivam.com

  peer4.org1.hf.Shivam.com:
    image: hyperledger/fabric-peer:x86_64-1.0.5
    container_name: peer4.org1.hf.Shivam.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_NETWORKID=Shivam
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
      - CORE_PEER_ID=peer4.org1.hf.Shivam.com
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_ADDRESS=peer4.org1.hf.Shivam.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer4.org1.hf.Shivam.com:7051
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_LOCALMSPID=org1.hf.Shivam.com
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
      - CORE_PEER_TLS_SERVERHOSTOVERRIDE=peer4.org1.hf.Shivam.com
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.hf.Shivam.com/peers/peer4.org1.hf.Shivam.com/msp:/var/hyperledger/msp
      - ./crypto-config/peerOrganizations/org1.hf.Shivam.com/peers/peer4.org1.hf.Shivam.com/tls:/var/hyperledger/tls
    ports:
      - 8041:7051
      - 8043:7053
    depends_on:
      - orderer.hf.Shivam.com
    links:
      - orderer.hf.Shivam.com
    networks:
      default:
        aliases:
          - peer4.org1.hf.Shivam.com
